### ISSUE TITLE
Error loading #all group of the baseline

### ISSUE THREAD

**Issue by tinchodias** [pavel-krivanek/Ring2#10]
In a Pharo 8.0 downloaded today, the error says that PBBootstrap and other 4 classes don't exist in the image. Missing depended project?

```
Metacello new
  baseline: 'Ring2';
  repository: 'github://pavel-krivanek/Ring2/src';
  load: #all.
```

**Comment by pavel-krivanek** [comment]
The #all group is loading the support for bootstrapping too that requires Pharo30Bootstrap package in the image

**Comment by tinchodias** [comment]
Thanks. Where is that package? However, I reported this issue for the case it's not expected. You can close the issue.

For the moment I just want to create a Ring2 environment from all the code in an IceCommit... if you have any pointer I'd be great. But this is not th eright forum, I should write you via chat or email, I guess.

**Comment by pavel-krivanek** [comment]
The package is in the main Pharo repository, in the bootstrap folder. If you will be able to create the MC snapshot from the commit then it will be very easy to import them into Ring model.
