### ISSUE TITLE
Crash on Pharo 8

### ISSUE THREAD

**Issue by tinchodias** [pavel-krivanek/Ring2#11]
In a Pharo 8 downloaded today, evaluate: `RGEnvironment new ensurePackageNamed: 'Hi'` And there is some infinite loop. 

I installed Ring2 with:
~~~
Metacello new
  baseline: 'Ring2';
  repository: 'github://pavel-krivanek/Ring2/src';
  load.
~~~

**Comment by tinchodias** [comment]
Just checked in P7 and didn't has this issue.

**Comment by pavel-krivanek** [comment]
load the branch `RGPackageRenamed`

**Comment by pavel-krivanek** [comment]
I updated the readme

**Comment by tinchodias** [comment]
It works! thanks!
I let you close it
